name: Reel Bot
on:
  #schedule:
  # - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Script
        env:
          INSTA_TOKEN: ${{ secrets.INSTA_TOKEN }}
        run: node post_reel.js
      - name: Save Repo
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "Cleanup posted reel" || exit 0
          git push
          
